# Generated by Django 5.2.8 on 2025-11-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.CharField(choices=[('mind', '🧠 Minte'), ('work', '💻 Muncă'), ('food', '🍽 Hrană'), ('sleep', '😴 Somn'), ('emotion', '💛 Emoții')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='planner.day')),
            ],
        ),
    ]
