# Generated by Django 5.2.8 on 2025-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='how_i_felt',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='day',
            name='day_type',
        ),
        migrations.RemoveField(
            model_name='day',
            name='sleep',
        ),
        migrations.AddField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'Verde'), ('yellow', 'Galben'), ('red', 'Roșu'), ('blue', 'Albastru'), ('purple', 'Mov')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='focus_of_the_day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='day',
            name='gratitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='day',
            name='mood',
            field=models.CharField(blank=True, choices=[('very_bad', '😞 Foarte greu'), ('bad', '😕 Greu'), ('neutral', '😐 Neutru'), ('good', '🙂 Bine'), ('very_good', '😄 Foarte bine')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='category',
            field=models.CharField(choices=[('work', 'Muncă'), ('personal', 'Personal'), ('health', 'Sănătate'), ('travel', 'Deplasare'), ('rest', 'Odihnă'), ('other', 'Altele')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
