# Generated by Django 5.2.8 on 2025-11-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_day_options_alter_timeblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='category',
        ),
        migrations.AddField(
            model_name='day',
            name='rest_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EveningReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drain', models.TextField(blank=True)),
                ('small_win', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evening_reflection', to='planner.day')),
            ],
        ),
    ]
