# Generated by Django 5.2.8 on 2025-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_day_user_alter_day_date_alter_day_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
