# Generated by Django 5.2.8 on 2025-11-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_userprofile_evening_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='closing_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days', to='planner.quote'),
        ),
    ]
