# Generated by Django 5.2.9 on 2025-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_day_closing_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='focus_of_the_day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='gratitude',
        ),
        migrations.RemoveField(
            model_name='timeblock',
            name='category',
        ),
        migrations.AlterField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
