# Generated by Django 5.2.8 on 2025-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day_type', models.CharField(choices=[('workday', 'Workday'), ('friday', 'Friday'), ('weekend', 'Weekend')], max_length=10)),
                ('mood', models.CharField(blank=True, choices=[('very_bad', '😞 Foarte greu'), ('bad', '😕 Greu'), ('neutral', '😐 Neutru'), ('good', '🙂 Ok'), ('very_good', '😄 Bine')], max_length=10, null=True)),
                ('sleep', models.CharField(blank=True, choices=[('poor', '4–6 ore'), ('ok', '7–9 ore'), ('long', '10+ ore')], max_length=10, null=True)),
                ('how_i_felt', models.TextField(blank=True)),
            ],
        ),
    ]
