# Generated by Django 5.2.8 on 2025-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('calm', 'Calm'), ('hope', 'Speranță'), ('grounding', 'Ancorare')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
