# Generated by Django 5.2.8 on 2025-11-26 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_delete_habit_rename_how_i_felt_day_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='day',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'Verde'), ('yellow', 'Galben'), ('red', 'Roșu'), ('blue', 'Albastru'), ('purple', 'Mov')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='mood',
            field=models.CharField(blank=True, choices=[('very_bad', '😞 Foarte greu'), ('bad', '😕 Greu'), ('neutral', '😐 Neutru'), ('good', '🙂 Bine'), ('very_good', '😄 Foarte bine')], max_length=20, null=True),
        ),
    ]
