# Generated by Django 5.2.8 on 2025-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_day_closed_at_day_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='evening_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('ea', 'ea / ei'), ('el', 'el / lui'), ('they', 'they')], max_length=10),
        ),
    ]
