# Generated by Django 5.2.8 on 2026-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_remove_day_focus_of_the_day_remove_day_gratitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='evening_reminder_time',
            field=models.TimeField(blank=True, help_text='Optional daily reminder time for evening reflection.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('she', 'she / her'), ('he', 'he / him'), ('they', 'they')], max_length=10),
        ),
    ]
