# Generated by Django 5.2.8 on 2026-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0016_seed_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Heavy"),
                    ("yellow", "Uneven"),
                    ("green", "Light"),
                    ("blue", "Calm"),
                    ("purple", "Creative"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_bad", "Very hard"),
                    ("bad", "Hard"),
                    ("neutral", "Neutral"),
                    ("good", "Good"),
                    ("very_good", "Very good"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
