# Generated by Django 5.2.8 on 2026-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0017_alter_day_color_alter_day_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_evening_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
