# Generated by Django 5.2.8 on 2026-09-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0018_userprofile_last_evening_reminder_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="rest_day",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pronoun",
        ),
    ]
