# Generated by Django 5.2.8 on 2026-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0019_remove_day_rest_day_remove_userprofile_pronoun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Heavy"),
                    ("yellow", "Uneven"),
                    ("green", "Light"),
                    ("blue", "Calm"),
                    ("purple", "Vivid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
